modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/CommandrMoose/Masters-Delight/issues" #optional

[[mods]] #mandatory
modId="master" #mandatory
version="0.0.1" #mandatory
displayName="The Master's Delight" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://tardis-mod.com/" #optional
logoFile="logo.png" #optional
credits="CommandrMoose" #optional
authors="CommandrMoose" #optional
description='''
The Master's Delight is an addon mod for the New TARDIS Mod.'''


[[dependencies.master]]
    modId="tardis"
    mandatory=true
    versionRange="[1.4,)"
    ordering="AFTER"
    side="BOTH"